(()=>{
'use strict';
const F=window.FuelOps,KEY='fuelops_suite_demo_v1';let state,filter='ALL',selected=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function esc(s){return String(s??'').replace(/[&<>\"']/g,function(c){if(c==='&')return '&amp;';if(c==='<')return '&lt;';if(c==='>')return '&gt;';if(c==='\"')return '&quot;';return '&#39;';});}
function load(){try{state=JSON.parse(localStorage.getItem(KEY))}catch(e){} if(!state)state=F.initialState()}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function openExceptions(){return state.exceptions.filter(e=>e.status!=='RESOLVED')}
function sortEx(a,b){const w={RED:2,AMBER:1};return(w[b.sev]-w[a.sev])||((b.exposure||0)-(a.exposure||0))}
function kpis(){const s=F.summary(state);const cards=[['Network sales',F.money(s.sales),'Synthetic today','good'],['Est. gross margin',F.money(s.margin),'Synthetic model','good'],['Open financial exposure',F.money(s.exposure),`${s.red} RED exceptions`,'bad'],['Sites requiring action',s.actionSites,`${s.open} open exceptions`,'warn'],['Cash reconciliation',F.money(openExceptions().filter(e=>e.cat==='Cash / bank').reduce((a,e)=>a+e.exposure,0)),'Expected vs verified','bad'],['Credit limit breach',F.money(openExceptions().filter(e=>e.cat==='Credit exposure').reduce((a,e)=>a+e.exposure,0)),'Human approval required','warn']];$('#kpis').innerHTML=cards.map(c=>`<article class=\"kpi ${c[3]}\"><span>${esc(c[0])}</span><strong>${esc(c[1])}</strong><small>${esc(c[2])}</small></article>`).join('');const h=[...openExceptions()].sort(sortEx)[0];$('#brief').textContent=h?`${28-s.actionSites}/28 sites clear of site-level exceptions. ${s.open} unresolved items. Highest exposure: ${h.site} — ${h.title} (${F.money(h.exposure||0)}).`:'All seeded exceptions are resolved.'}
function exceptions(){const list=openExceptions().filter(e=>filter==='ALL'||e.sev===filter).sort(sortEx);$('#exceptions').innerHTML=list.length?list.map(e=>`<button class=\"ex\" data-id=\"${e.id}\"><b class=\"sev ${e.sev}\">${e.sev}</b><span><strong>${esc(e.site)}</strong><small>${esc(e.cat)}</small></span><span class=\"grow\"><strong>${esc(e.title)}</strong><small>${esc(e.trigger)}</small></span><span class=\"exp\">${e.exposure?F.money(e.exposure):'Control risk'}</span><span class=\"arrow\">Open →</span></button>`).join(''):'<div class=\"empty\">No unresolved exceptions in this filter.</div>';$$('.ex').forEach(x=>x.onclick=()=>drawer(x.dataset.id))}
function sites(q=''){q=q.trim().toLowerCase();const rows=state.sites.filter(s=>!q||[s.id,s.name,s.region,s.manager].some(v=>v.toLowerCase().includes(q)));$('#sitesBody').innerHTML=rows.map(s=>`<tr><td><b>${s.name}</b><small>${s.id}</small></td><td>${s.region}</td><td>${s.manager}</td><td>${F.money(s.sales)}</td><td>${F.money(s.margin)}</td><td>${s.petrol.toLocaleString()}</td><td>${s.hsd.toLocaleString()}</td><td>${s.close}</td><td class=\"health ${s.health}\">${s.health}</td></tr>`).join('')}
function audit(){const seeded=state.exceptions.flatMap(e=>e.audit.map(a=>({at:a[0],id:e.id,actor:a[1],action:a[2]}))),dyn=(state.actions||[]).slice().reverse();$('#auditBody').innerHTML=[...dyn,...seeded.reverse()].map(a=>`<tr><td>${esc(a.at)}</td><td>${esc(a.id)}</td><td>${esc(a.actor)}</td><td>${esc(a.action)}</td></tr>`).join('')}
function action(e,actor,text){state.actions=state.actions||[];state.actions.push({at:new Date().toLocaleString('en-PK',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'short'}),id:e.id,actor,action:text});save()}
function drawer(id){selected=id;const e=state.exceptions.find(x=>x.id===id);if(!e)return;$('#backdrop').classList.add('show');$('#drawer').classList.add('show');$('#drawer').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';$('#drawerHead').innerHTML=`<div><b class=\"sev ${e.sev}\">${e.sev}</b> <span class=\"pill\">${esc(e.status)}</span></div><button id=\"closeDrawer\">Close</button>`;$('#drawerBody').innerHTML=`<p class=\"meta\">${esc(e.site)} · ${esc(e.cat)} · ${esc(e.id)}</p><h2>${esc(e.title)}</h2><div class=\"trigger\"><b>Deterministic trigger:</b> ${esc(e.trigger)}</div><div class=\"detail\"><div><span>Financial exposure</span><strong>${e.exposure?F.money(e.exposure):'Control risk'}</strong></div><div><span>Accountable role</span><strong>${esc(e.owner)}</strong><small>Due: ${esc(e.due)}</small></div></div><h3>Calculation / rule evidence</h3><div class=\"formula\">${e.formula.map(r=>`<div><span>${esc(r[0])}</span><b>${esc(r[1])}</b></div>`).join('')}</div><h3>Evidence attached</h3><div class=\"evidence\">${e.evidence.map(x=>`<div>✓ ${esc(x)}</div>`).join('')}</div><h3>Manager / responsible response</h3><textarea id=\"note\" placeholder=\"Add synthetic response or owner note…\">${esc(e.response||'')}</textarea><div class=\"actions\"><button class=\"primary\" id=\"saveNote\">Save response</button>${e.status==='RESOLVED'?'<button id=\"reopen\">Reopen</button>':'<button id=\"request\">Request explanation</button><button class=\"danger\" id=\"resolve\">Resolve exception</button>'}</div><p class=\"hint\">Synthetic demo only. No message, bank action, payment or external workflow is performed.</p><h3>Audit trail</h3><div class=\"timeline\">${[...e.audit,...((state.actions||[]).filter(a=>a.id===e.id).map(a=>[a.at,a.actor,a.action]))].map(a=>`<div><b>${esc(a[2])}</b><small>${esc(a[0])} · ${esc(a[1])}</small></div>`).join('')}</div>`;$('#closeDrawer').onclick=close;$('#saveNote').onclick=()=>{e.response=$('#note').value.trim();action(e,'Owner','Saved response / note');refresh();drawer(e.id)};const rq=$('#request');if(rq)rq.onclick=()=>{e.status='EXPLANATION REQUESTED';action(e,'Owner','Requested explanation from accountable role');refresh();drawer(e.id)};const rs=$('#resolve');if(rs)rs.onclick=()=>{e.status='RESOLVED';action(e,'Owner','Resolved exception after review');refresh();drawer(e.id)};const ro=$('#reopen');if(ro)ro.onclick=()=>{e.status='OPEN';action(e,'Owner','Reopened exception');refresh();drawer(e.id)}}
function close(){$('#backdrop').classList.remove('show');$('#drawer').classList.remove('show');$('#drawer').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1700)}
function refresh(){kpis();exceptions();sites($('#search').value||'');audit();save()}
load();$$('.filter').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x===b));exceptions()});$('#search').oninput=e=>sites(e.target.value);$('#backdrop').onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});$('#reset').onclick=()=>{if(confirm('Reset local synthetic demo state?')){localStorage.removeItem(KEY);state=F.initialState();filter='ALL';refresh();close()}};$$('[data-go]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.go).scrollIntoView({behavior:'smooth'}));$$('[data-pulse]').forEach(b=>b.onclick=()=>{if(b.dataset.pulse==='fuel'){document.getElementById('attention').scrollIntoView({behavior:'smooth'});toast('Fuel exception control opened')}else if(b.dataset.pulse==='solar'){filter='AMBER';$$('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter==='AMBER'));exceptions();document.getElementById('attention').scrollIntoView({behavior:'smooth'});toast('Solar exception highlighted')}else{toast('LED / Projects is status-only in Demo V1')}});refresh();
})();
