(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.FuelOps=factory()})(typeof self!=='undefined'?self:this,function(){
'use strict';
const money=n=>'Rs '+Math.round(n).toLocaleString('en-PK');
function calcStock({opening,delivery,sales,physical,unitCost}){const expected=opening+delivery-sales,variance=physical-expected;return{expected,variance,exposure:Math.abs(variance)*unitCost}}
function calcCash({expected,deposit}){return{variance:deposit-expected,exposure:Math.abs(deposit-expected)}}
function calcCredit({outstanding,limit}){return{excess:Math.max(0,outstanding-limit),exposure:Math.max(0,outstanding-limit)}}
function makeSites(){return Array.from({length:28},(_,i)=>{const n=i+1,sales=1000000+n*41000+((n*9700)%180000);return{id:`P${String(n).padStart(2,'0')}`,name:`Fuel Site ${String(n).padStart(2,'0')}`,region:['North','Central','South','East'][i%4],manager:`Manager ${String(n).padStart(2,'0')}`,sales,margin:Math.round(sales*(.046+(n%4)*.002)),petrol:3300+((n*173)%1700),hsd:4100+((n*211)%2100),close:n===3?'23:47':`22:${String((n*7)%60).padStart(2,'0')}`,health:[7,14].includes(n)?'RED':[3,19,21].includes(n)?'AMBER':'NORMAL'}})}
function makeExceptions(){const f=calcStock({opening:18500,delivery:12000,sales:9875,physical:20020,unitCost:286}),c=calcCash({expected:1145000,deposit:1060000}),cr=calcCredit({outstanding:1460000,limit:1000000});return[
{id:'EX-007-HSD',sev:'RED',cat:'Fuel variance',site:'Fuel Site 07',siteId:'P07',title:'HSD closing stock below expected balance',owner:'Manager 07',status:'OPEN',due:'Immediate',exposure:f.exposure,trigger:`Physical stock is ${Math.abs(f.variance).toLocaleString()} L below expected closing; tolerance 100 L.`,formula:[['Opening stock','18,500 L'],['+ Delivery','12,000 L'],['− Metered sales','9,875 L'],['= Expected closing',`${f.expected.toLocaleString()} L`],['Physical closing','20,020 L'],['Variance',`${f.variance.toLocaleString()} L`],['Unit cost','Rs 286/L'],['Exposure',money(f.exposure)]],evidence:['Shift close #P07-N2','Tank dip photo — synthetic','Delivery challan #SYN-1842','Nozzle meter close — synthetic'],response:'Tank dip repeated after shift close; evidence attached.',audit:[['22:12','Shift Operator 07','Submitted shift close'],['22:13','Rule Engine','Created RED stock exception'],['22:21','Manager 07','Added response + evidence']]},
{id:'EX-014-CASH',sev:'RED',cat:'Cash / bank',site:'Fuel Site 14',siteId:'P14',title:'Verified deposit below expected cash',owner:'Finance + Manager 14',status:'OPEN',due:'Today',exposure:c.exposure,trigger:`Verified deposit is ${money(Math.abs(c.variance))} below expected shift cash.`,formula:[['Expected cash',money(1145000)],['Verified deposit',money(1060000)],['Variance',money(c.variance)],['Exposure',money(c.exposure)]],evidence:['Shift settlement #P14-D1','Synthetic deposit slip #DEP-441','Card settlement summary'],response:'',audit:[['18:05','Finance Import','Matched verified deposit'],['18:05','Rule Engine','Created RED cash mismatch']]},
{id:'EX-GRP-CREDIT',sev:'RED',cat:'Credit exposure',site:'Group Credit',siteId:'GROUP',title:'Fleet Customer A above approved credit limit',owner:'Finance Head',status:'OWNER REVIEW',due:'Before next credit sale',exposure:cr.exposure,trigger:`Outstanding exceeds approved limit by ${money(cr.excess)}.`,formula:[['Approved limit',money(1000000)],['Outstanding',money(1460000)],['Limit breach',money(cr.excess)]],evidence:['Synthetic customer ledger','Synthetic approved credit profile'],response:'No autonomous override; authorized human approval required.',audit:[['17:40','Credit Ledger','Outstanding updated'],['17:40','Rule Engine','Created RED credit breach']]},
{id:'EX-021-SOLAR',sev:'AMBER',cat:'Solar performance',site:'Fuel Site 21',siteId:'P21',title:'Solar generation 38% below baseline',owner:'Solar Team',status:'OPEN',due:'Today',exposure:0,trigger:'Actual generation 508 kWh vs synthetic expected 820 kWh.',formula:[['Expected','820 kWh'],['Actual','508 kWh'],['Shortfall','312 kWh'],['Below baseline','38%']],evidence:['Synthetic inverter summary','Synthetic normalized baseline'],response:'',audit:[['16:00','Solar Import','Created AMBER generation exception']]},
{id:'EX-003-LATE',sev:'AMBER',cat:'Shift control',site:'Fuel Site 03',siteId:'P03',title:'Night shift close submitted 47 minutes late',owner:'Manager 03',status:'OPEN',due:'Explain',exposure:0,trigger:'Closure submitted after configured 23:00 deadline.',formula:[['Deadline','23:00'],['Submitted','23:47'],['Delay','47 min']],evidence:['System timestamp'],response:'',audit:[['23:47','Rule Engine','Created AMBER late-close exception']]},
{id:'EX-019-ASSET',sev:'AMBER',cat:'Asset fault',site:'Fuel Site 19',siteId:'P19',title:'One HSD nozzle unavailable',owner:'Maintenance',status:'MAINTENANCE ASSIGNED',due:'4 hours',exposure:0,trigger:'Nozzle N-04 unavailable for >60 minutes.',formula:[['Asset','HSD Nozzle N-04'],['Threshold','60 min'],['State','Unavailable']],evidence:['Fault ticket #FT-019-04','Synthetic operator photo'],response:'Technician assigned in demo workflow.',audit:[['14:10','Operator 19','Reported nozzle unavailable'],['15:11','Rule Engine','Created AMBER downtime exception'],['15:20','Operations','Assigned Maintenance']]}
]}
function initialState(){return{sites:makeSites(),exceptions:makeExceptions(),actions:[]}}
function summary(s){const open=s.exceptions.filter(e=>e.status!=='RESOLVED');return{sales:s.sites.reduce((a,x)=>a+x.sales,0),margin:s.sites.reduce((a,x)=>a+x.margin,0),exposure:open.reduce((a,x)=>a+(x.exposure||0),0),open:open.length,red:open.filter(x=>x.sev==='RED').length,amber:open.filter(x=>x.sev==='AMBER').length,actionSites:new Set(open.map(x=>x.siteId).filter(x=>x!=='GROUP')).size}}
return{money,calcStock,calcCash,calcCredit,makeSites,makeExceptions,initialState,summary};
});
